name: flutter_money_manager
description: "A new Flutter project that related with money manager expense and budget"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  iconly: ^1.0.1
  easy_date_timeline: ^2.0.9
  flutter_datetime_picker_plus: ^2.2.0
  provider: ^6.1.4
  go_router: ^14.8.1
  table_calendar: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/
  fonts:
    - family: Cormorant
      fonts:
        - asset: assets/fonts/cormorant/CormorantInfant-Bold.ttf
          weight: 700
        - asset: assets/fonts/cormorant/CormorantInfant-Italic.ttf
          weight: 200
        - asset: assets/fonts/cormorant/CormorantInfant-Light.ttf
          weight: 300
        - asset: assets/fonts/cormorant/CormorantInfant-LightItalic.ttf
          weight: 500
        - asset: assets/fonts/cormorant/CormorantInfant-Medium.ttf
          weight: 600
        - asset: assets/fonts/cormorant/CormorantInfant-MediumItalic.ttf
          weight: 800
        - asset: assets/fonts/cormorant/CormorantInfant-Regular.ttf
          weight: 900
        - asset: assets/fonts/cormorant/CormorantInfant-SemiBold.ttf
          weight: 100
        - asset: assets/fonts/cormorant/CormorantInfant-SemiBoldItalic.ttf